# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-yaml
- repo: https://github.com/kynan/nbstripout
  rev: master
  hooks:
    - id: nbstripout
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.3.5
  hooks:
    - id: nbqa-pyupgrade
      args: [--nbqa-mutate]
    - id: nbqa-black
      args: [--nbqa-mutate]
    # - id: nbqa-isort
    #   args: [--nbqa-mutate]
    # - id: nbqa-flake8
